### ISSUE TITLE
Bug: module-templates.templateFiles cannot read templates folder

### ISSUE THREAD

**Issue by webdog** [asbjornh/vscode-module-templates#13]
Hi there! This is a cool extension, but I can't get `templateFiles` to load templates in my environment. I've tried a code-workspace, a single folder, and a multi-root workspace. In all circumstances, the extension cannot read the directory and silently fails. `templateFiles` always fails, whether or not the `templates` key is present in the workspace or local settings, and also prevents the extension from working when `templates` key is present.

VSCode:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

* Create a template in a defined template directory inside of a project or workspace i.e. `.templates/myTemplate.json`, which matches the schema listed for [`module-templates.templates`](https://github.com/asbjornh/vscode-module-templates#module-templatestemplates)
```
{
    "displayName": "My Filename",
    "questions": {
        "name": "File Name"
    },
    "files": [
        {
          "name": "file-example.md",
          "content": [
              "Sample content"
          ]
        }
      ]
}
```

* Configure `code-workspace.json` or `.vscode/settings.json` with absolute or relative path of templates folder:
 (Note: I tried both using `templates` and `templates/` with the trailing slash.)
```
{
    "module-templates.engine": "handlebars",
    "module-templates.templateFiles": ["/Users/webdog/test/.templates/"]
}
```

* Save and reload
* Navigate to file explorer, and select `New From Template` - In Developer Tools, this generates a Stack Trace, but no error is reported to the User:

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: /Users/webdog/test/.templates: EISDIR: illegal operation on a directory, read


console.ts:137 [Extension Host] stack trace: Error: /Users/webdog/test/.templates: EISDIR: illegal operation on a directory, read
at Object.readSync (fs.js:506:3)
at tryReadSync (fs.js:331:20)
at Object.readFileSync (fs.js:368:19)
at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
at Object.readFileSync (/Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:45833)
at Object.e.readJson (/Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:9576)
at /Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:122304	
at Array.map (<anonymous>)
at Object.<anonymous> (/Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:122286)
at Generator.next (<anonymous>)
at /Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:121601
at new Promise (<anonymous>)
at n (/Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:121346)
at Object.e.default (/Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:122183)
at /Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:25429
at Generator.next (<anonymous>)
at s (/Users/webdog/.vscode/extensions/asbjornh.vscode-module-templates-1.3.0/dist/extension.js:1:24656)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

What I've confirmed/tried:

* Tried using hidden and non-hidden folder syntax (templates vs .templates directory)
* Confirmed on two separate installs of VSCode (Boths Macs, same version)
* Confirmed the read permissions on the folder.
* Tried multi-root and single folder workspace, as well as a single folder with a `.vscode/settings.json` file present

Thanks!

**Comment by asbjornh** [comment]
Hi!

Did you try using a file path instead of a folder path in `templateFiles`? The documentation is not very clear on that point

**Comment by webdog** [comment]
@asbjornh That fixed it, thank you!

One additional note: When I referenced the path of the of the template, it found the file, but initially complained that the template file was not a JSON Array.

When I looked up the [docs](https://github.com/asbjornh/vscode-module-templates#module-templatestemplatefiles) about `templateFiles` I came across the schema definition note:

>... The files must be json files and the contents must match the schema of the module-templates.templates option.

I understood this as being able to create a JSON object as the file contents. In order to get it to work, I had to encapsulate the Object into an Array, such as:

![image](https://user-images.githubusercontent.com/960210/97815817-817ab580-1c56-11eb-91e2-2cbe40524a03.png)


I'm not sure if this was by design or not (I was assuming the extension would do this encapsulation for me as it read the template file), but just figured you might appreciate the feedback 😺 

Thanks again for this extension!

**Comment by asbjornh** [comment]
Yeah, the schema for the `module-templates.templates` option is an array of template objects as stated [here](https://github.com/asbjornh/vscode-module-templates#module-templatestemplates). I think I should update the docs for the `templateFiles` option though to make it more clear that file paths must be passed.
