### ISSUE TITLE
Modify a file

### ISSUE THREAD

**Issue by fjbardelli** [asbjornh/vscode-module-templates#14]
Hello, this extension is great.

It is possible when adding a file, modify another by adding an import for example.

Thank you

**Comment by asbjornh** [comment]
Hey!

I guess in theory anything's possible, but I don't really see how that could be implemented in a nice way for this extension. I'm open to suggestions

**Comment by pksunkara** [comment]
Can we use jscodemod?

**Comment by asbjornh** [comment]
There's probably a number of tools that could be used (babel comes to mind), but I have trouble envisioning a json API for something like that. Also I feel like transforming existing source code is well outside of the realm of a templating tool.

If there are things that can be done to help integrate other tools with this extension I think that could make sense, although I have no experience with that.

**Comment by asbjornh** [comment]
I'm going to close this. This feature feels way outside the scope of this extension
