### ISSUE TITLE
Can't merge user and workspace settings

### ISSUE THREAD

**Issue by pksunkara** [asbjornh/vscode-module-templates#16]
I have some user templates and I am setting up some project related templates. But since the `templates` setting is an array, I can't use the global user templates in that project.

From vscode [docs](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence):

> Values with primitive types and Array type are overridden but those with Object type are merged

I would propose adding a new templates setting to be an object with template `id` as key which should take preference over the current existing setting.

I am willing to make a PR if you agree.

**Comment by asbjornh** [comment]
I think that makes sense, yeah. I’m happy to accept that change :)
