### ISSUE TITLE
Alternate template definition formats

### ISSUE THREAD

**Issue by pagameba** [asbjornh/vscode-module-templates#19]
Hi, I love this extension but I find trying to set up templates for files a bit tiresome and error prone using the JSON syntax because it doesn't support multi-line strings or using single quotes.  I have a couple of suggestions.

1. Allow specifying a `js` file for templateFiles that exports the templates as an object.  This would allow use of backticks to embed multi-line strings which would make the templates a lot easier to write and read.
2. Allow specifying a file on disk as the template as the source for the template, or even a folder structure that could be used, this would also make creating and reasoning about more complex template structures a lot easier.

**Comment by asbjornh** [comment]
Hi!

Truth be told I never considered that people would be making templates for JSON _in_ JSON when I made this! That does sound horrible.

I think an option for reading a single template from disk makes a lot of sense. That could also help keep the size of the config down when working with large templates. I don't understand what a solution involving folder structure would even look like though. Would you care to elaborate?

**Comment by pagameba** [comment]
What I was thinking was that the settings could contain a `templateRoot` (or probably a better name) which would point to a folder relative to the settings file. Every folder and file within that root would then be used to generate the template.  For  me, I am templating out lambda functions for use with AWS SAM and the functions have a very specific folder structure I want to create. 

```
"module-templates.templateRoot": "templates/sam-function",
```

```
settings.json
templates/
  sam-function/
    package.json
    README.md
    babel.config.js
    jest.config.js
    .npmrc
    handler.js
    index.js
    __tests__
      handler.spec.js
   __mocks__
     axios.js
```  

Thinking more about this though, I think this would be less useful than using a `js` configuration file because you wouldn't be able to template the file names which is something I'm currently doing.

**Comment by asbjornh** [comment]
I see. Yeah the file and folder names would be a concern.

What I was thinking was instead of injecting arbitrary js code there could be a “templateFile” option for files, optionally used instead of the “content” option. That file would be read as a string and treated the same way as “content”.

It seems to me that that would solve the issue. What do you think?

**Comment by pagameba** [comment]
That could work.

**Comment by asbjornh** [comment]
I've released version 1.8.0 of this extension. It's now possible to specify a `contentFile` instead of `content`, that points to a file to read a template from. Hope this helps!

**Comment by pagameba** [comment]
🥇 thanks, will try it out!

**Comment by pagameba** [comment]
works like a charm!

**Comment by asbjornh** [comment]
Great 😄
