### ISSUE TITLE
Move button from top of list

### ISSUE THREAD

**Issue by Kampfkarren** [asbjornh/vscode-module-templates#21]
When you right-click to create a new file, New File From Template is the top of the list. This messes with the muscle memory I've been trained on for VS Code, and is not comfortable. I would like it moved lower on the list, or configurable if this is not too much maintenance.

**Comment by asbjornh** [comment]
Hey! I agree. I'm not sure if changing the order of menu items was supported when this extension was created initially, but it is supported now so I'll get on that

**Comment by asbjornh** [comment]
Fixed in 1.6.0. Should be available on the Marketplace soon

**Comment by Kampfkarren** [comment]
Thanks for the wicked fast response time!
