### ISSUE TITLE
Allow for creation of subfolders and files in them

### ISSUE THREAD

**Issue by cgmonroe** [asbjornh/vscode-module-templates#22]
It would be nice if this could create subfolders and files in them.  E.g.:

```
module_name
  module1.file
  module2.file
  css
   module.css
  js
    module.js
 src
   Controller
     ControllerStub.xxx
```

I could see the template syntax for this being something like:

```
"folder": [
  "{{base}}",
  "{{base}}/css",
  "{{base}}/js",
  "{{base}}/src",
  "{{base}}/src/Controller"
]
"files": [
  "name": "{{base}}.css,
  "folder":  "{{base}}/css",
```

The folders array would be nice if empty folders are needed.  But it might be quicker just to implement the folder option for files and use the to create any parent directories when the file is created.

**Comment by asbjornh** [comment]
Hi!

This is already possible. You can add extra folders with the `name` option, like so:
`css/module.css`, which would create the folder `css` with the file `module.css` inside of it. Paths can be any depth.

I think that’s mentioned in the docs? If not it probably should be.

**Comment by cgmonroe** [comment]
In the immortal words of Rosanne Rosanna Danna.... Never mind... :)

Thanks for the info.  FYI - It is documented in the name attribute of the file but I missed it.

Closing this issue.

Thanks for this wonderful time saving extension!

**Comment by asbjornh** [comment]
Oh good. I did remember to do that then 😄
