### ISSUE TITLE
Create files depending on questions

### ISSUE THREAD

**Issue by pksunkara** [asbjornh/vscode-module-templates#27]
I have a template for which I want to ask a question whether they want a test file to be created or not. But I don't see a way to take the answer from the question and then not creating that file.

Would be happy to contribute a PR, but WDYT?

**Comment by asbjornh** [comment]
Hey! This should already be possible by creating a template that inherits your template and adds an extra test file. See the “extends” option on templates.

let me know if there are technical issues there because this is the intended use case for that feature

**Comment by pksunkara** [comment]
Hmm.. I am not sure how that would work.

Let's say I have a template `A` that creates file `A.js`. Now, I want to ask a question `add test file?`. If the answer is yes, I want to create a `A.test.js` file too. If not I will just create the `A.js` only.

I am not talking about 2 different templates but just one.

**Comment by asbjornh** [comment]
Yeah, I gotcha. So then you could create an “A” template, and another “A with test” template that extends A but also adds a test file. Then you pick the one you need in the list of templates

**Comment by pksunkara** [comment]
> Then you pick the one you need in the list of templates

Yeah that is what I was trying to avoid since I want to add another similar question for another file which multiplies this combination quite a lot more..

**Comment by asbjornh** [comment]
So it seems like you want a different API for something the extension can already do. Fair enough, but tbh this feels a bit like an edge case. If this request turns out to be popular I’ll consider it.

Let’s just keep this issue open and see.

**Comment by thanhngochoang** [comment]
I have a template, All of the files look like templates with the same parameters. Then I use “extends” in the final template. then it's good works for a file. 
I must do it many times. Maybe the result of the question is an array, I can apply the config to iterate for a template.

**Comment by pksunkara** [comment]
> I must do it many times. 

Yeah, that is what made me create this issue. Because if there are two optional files, the extend would need us to create 4 templates

**Comment by pksunkara** [comment]
@asbjornh Will you accept a contribution for this?

**Comment by pksunkara** [comment]
Implemented this with a simple change in #33. Would appreciate if @asbjornh can take a look.
