### ISSUE TITLE
How can I create a folder structure from a template?

### ISSUE THREAD

**Issue by dmnphpkmnr** [asbjornh/vscode-module-templates#28]
I want to create a template which would generate a folder tree, such as the following:
(some folder would be empty; other folders might contain template files)

```
- app
--- assets
------ images
------ fonts
--- src
------ components
---------- atoms
---------- molecules
...
```

Is that possible?

**Comment by asbjornh** [comment]
Hey! You can’t create a nested structure of empty folders using this plugin, no. You can however create a nested structure of non-empty folders, by putting paths for the names of the files you’re creating.
