### ISSUE TITLE
Add placeholder for the current year

### ISSUE THREAD

**Issue by ThiefMaster** [asbjornh/vscode-module-templates#3]
For example, one of my projects uses this header in its files:

```js
// This file is part of XXX.
// Copyright (C) 2002 - 2020 YYY
//
// XXX is free software; you can redistribute it and/or
// modify it under the terms of the MIT License; see the
// LICENSE file for more details.
```

Having a placeholder like `{year} would avoid having to update all the templates once a year.

**Comment by asbjornh** [comment]
Sorry for the late reply.

I'm a little bit sceptical about adding this. Having just a `{year}` token on its own would be really strange. If I were to add something like this there would have to be a proper set of options and I'm not too excited about going down the rabbit hole of time string formatting

**Comment by asbjornh** [comment]
1.7.0 added support for passing your own helpers and partials when using Handlebars templates. Adding your own `year` helper is now possible (and easy). I recommend migrating your templates to Handlebars!
