### ISSUE TITLE
Create the files in selected folder instead of default path when using keybinding or command palette.

### ISSUE THREAD

**Issue by pksunkara** [asbjornh/vscode-module-templates#34]
Currently, there is no way of getting the selected folder in explorer view, but there is a workaround which seems to be working as documented in https://github.com/microsoft/vscode/issues/3553#issuecomment-1098562676.

1. Implement the workaround
2. Use the selected folder/file from explorer or currently active document in text editor. Uses default path only when both of them are not present.
3. If a file is selected, create in the parent folder.

I would be willing to contribute a PR if this is okay with you @asbjornh. Also, please let add me as a maintainer if you are not maintaining this extension anymore.

**Comment by asbjornh** [comment]
This would be a nice feature if/when the vscode api exposes the current folder!
