### ISSUE TITLE
Handle template without initial question

### ISSUE THREAD

**Issue by abumalick** [asbjornh/vscode-module-templates#4]
I used your extension to add a `.prettierrc` file to my projects, can we disable the initial question? I don't need to name the file.

Thank you for the plugin

**Comment by asbjornh** [comment]
I didn't really consider that use case, but that's a good point! The plugin supports user-defined questions so there's really no need to have any hard-coded questions like `{name}`. I'll look into it.

**Comment by asbjornh** [comment]
Version `1.0.0` is now published. It no longer asks for a name, unless there exists a `name` property in `questions`.

**Comment by abumalick** [comment]
Thank you very much 👍
