### ISSUE TITLE
Feature: extend questions, maybe with back compatibility, to support "menu"

### ISSUE THREAD

**Issue by gremo** [asbjornh/vscode-module-templates#6]
First: thanks for this extension! It works well, I tried a lot of them, and then I came into this!

It could be a good feature to add a menu-style question type. I think that could be inferred from the question type itself. Example:

```json5
"questions": {
    // This is the "standard" question, like it works now
    "className": "Please input the class name",

    // This is the "extended" version: infer the type from the value (same as className)
    // No value provided, same as above
    "className2": {
        "title": "Please input the class name"
        "value: "", // user can provide a default value
     },

    // Make a choice menu if value is an array
     "type": {
        "title": "Type of the component?"
        "value: ["abstract class", "class", "interface", "trait"],
     },

     // Or even better, provide an object where key is the value, name is display name
     "type": {
        "title": "Type of the component?"
        "value: {
            "key": "trait",
            "display": "PHP trait"
        },
     },
}
```

This could be extended to `bool` also. What do you think?

**Comment by asbjornh** [comment]
I think something like this could make sense yes. I’m currently experimenting with adding mustache for richer templates. Right now that has higher priority so this might take a while :)

**Comment by gremo** [comment]
Great! Glad to hear... why mustache by the way?

**Comment by asbjornh** [comment]
Because I want backwards compatibility for the template syntax and most js templating engines don’t seem to have configurable tags

**Comment by asbjornh** [comment]
This is now supported in `1.2.0`! See https://github.com/asbjornh/vscode-module-templates#questions

**Comment by gremo** [comment]
Amazing job!!! I was reading the updated readme, can’t wait for tomorrow to test the new features!
