### ISSUE TITLE
Feature: ability to define templates in a separate file

### ISSUE THREAD

**Issue by gremo** [asbjornh/vscode-module-templates#7]
Using the workspace settings.json is a good think in order to share templates with the team. However, with a lot of templates, things could be messy.

What about letting choose if templates are provided using an external json file? For example:

```json5
// Relative path
"module-templates.templates.external": ".vscode/templates.json",

// Maybe support for ${workspaceFolder}?
"module-templates.templates.external": "${workspaceFolder}/vscode-templates.json",
```

**Comment by asbjornh** [comment]
I could try something like this, yes. I do foresee some difficulties in resolving file paths for things like user settings and multi-root workspaces though, so I can’t promise anything :)

Also, as per [this comment](https://github.com/asbjornh/vscode-module-templates/issues/6#issuecomment-637111226) I probably won’t attempt this right away

**Comment by asbjornh** [comment]
Supported in `1.2.0`. See https://github.com/asbjornh/vscode-module-templates#module-templatestemplatefiles
